const DELETE_LOGED_USER_TYPE = 'DELETE_LOGED_USER';
const SET_PAGE_TYPE = 'SET_PAGE';
const SET_ARTICLES_FOR_PAGE_TYPE = 'SET_ARTICLES_FOR_PAGE';
const SET_ARTICLES_LOADING_TYPE = 'SET_ARTICLES_LOADING';
const ERROR_GET_ARTICLES_FOR_PAGE_TYPE = 'ERROR_GET_ARTICLES_FOR_PAGE';
const SET_SIGN_UP_USERNAME_TYPE = 'SET_SIGN_UP_USERNAME';
const SET_SIGN_UP_EMAIL_TYPE = 'SET_SIGN_UP_EMAIL';
const SIGN_UP_PASSWORD_TYPE = 'SIGN_UP_PASSWORD';
const SIGN_UP_REPEAT_PASSWORD_TYPE = 'SIGN_UP_REPEAT_PASSWORD';
const TOOGLE_SIGN_UP_AGREEMENT_TYPE = 'TOOGLE_SIGN_UP_AGREEMENT';
const CLEAR_SIGN_UP_REDUCER_TYPE = 'CLEAR_SIGN_UP_REDUCER';
const SET_SIGN_IN_PASSWORD_OR_EMAIL_INCORRECT_TYPE = 'SET_SIGN_IN_PASSWORD_OR_EMAIL_INCORRECT';
const CLEAN_SIGN_IN_REDUCER_TYPE = 'CLEAN_SIGN_IN_REDUCER';
const SET_EDIT_PROFILE_SUCCES_TYPE = 'SET_EDIT_PROFILE_SUCCES';
const SET_SIGN_IN_UNEXPECTED_ERROR_TYPE = 'SET_SIGN_IN_UNEXPECTED_ERR';
const SET_EDIT_PROFILE_UNEXPECTED_ERROR_TYPE = 'SET_EDIT_PROFILE_UNEXPECTED_ERROR';
const CLEAR_EDIT_PROFILE_REDUCER_TYPE = 'CLEAR_EDIT_PROFILE_REDUCER';
const SET_SIGN_IN_EMAIL_TYPE = 'SET_SIGN_IN_EMAIL';
const SET_SIGN_IN_PASSWORD_TYPE = 'SET_SIGN_IN_PASSWORD';
const SET_LOGED_USER_TYPE = 'SET_LOGED_USER';
const SET_SIGN_UP_ERRORS_TYPE = 'SET_SIGN_UP_ERRORS';
const SET_EDIT_PROFILE_ERRORS_TYPE = 'SET_EDIT_PROFILE_ERRORS';
const SET_UNEXPECTED_ERROR_TYPE = 'SET_UNEXPECTED_ERROR';
const ADD_TAG_TYPE = 'ADD_TAG';
const SET_TYPED_IN_TAG_TYPE = 'SET_TYPED_IN_TAG';
const CLEAR_TYPED_IN_TAG_TYPE = 'CLEAR_TYPED_IN_TAG';
const DELETE_LAST_TAG_TYPE = 'DELETE_LAST_TAG';
const SET_CREATE_ARTICLE_SUCCES_TYPE = 'SET_CREATE_ARTICLE_SUCCES';
const SET_CREATE_ARTICLE_UNEXPECTED_ERROR_TYPE = 'SET_CREATE_ARTICLE_UNEXPECTED_ERROR';
const SET_ARTICLE_TYPE = 'SET_ARTICLE';
const CLEAR_ARTICLE_TYPE = 'CLEAR_ARTICLE';
const SET_ARTICLE_NOT_FOUND_TYPE = 'SET_ARTICLE_NOT_FOUND';
const SET_ARTICLE_UNEXPECTED_ERROR_TYPE = 'SET_ARTICLE_UNEXPECTED_ERROR';
const SET_DELETE_ARTICLE_ERR_TYPE = 'SET_DELETE_ARTICLE_ERR';
const SET_DELETE_ARTICLE_SUCCES_TYPE = 'SET_DELETE_ARTICLE_SUCCES';
const TOOGLE_SHOW_DELETE_CONFIRM_TYPE = 'TOOGLE_SHOW_DELETE_CONFIRM';
const CLEAR_DELETE_ARTICLE_REDUCER_TYPE = 'CLEAR_DELETE_ARTICLE_REDUCER';
const CLEAR_CREATE_ARTICLE_REDUCER_TYPE = 'CLEAR_CREATE_ARTICLE_REDUCER';

export {
  DELETE_LOGED_USER_TYPE,
  SET_PAGE_TYPE,
  SET_ARTICLES_FOR_PAGE_TYPE,
  SET_ARTICLES_LOADING_TYPE,
  ERROR_GET_ARTICLES_FOR_PAGE_TYPE,
  SET_SIGN_UP_USERNAME_TYPE,
  SET_SIGN_UP_EMAIL_TYPE,
  SIGN_UP_PASSWORD_TYPE,
  SIGN_UP_REPEAT_PASSWORD_TYPE,
  TOOGLE_SIGN_UP_AGREEMENT_TYPE,
  CLEAR_SIGN_UP_REDUCER_TYPE,
  SET_SIGN_IN_PASSWORD_OR_EMAIL_INCORRECT_TYPE,
  CLEAN_SIGN_IN_REDUCER_TYPE,
  SET_EDIT_PROFILE_SUCCES_TYPE,
  SET_SIGN_IN_UNEXPECTED_ERROR_TYPE,
  SET_EDIT_PROFILE_UNEXPECTED_ERROR_TYPE,
  CLEAR_EDIT_PROFILE_REDUCER_TYPE,
  SET_SIGN_IN_EMAIL_TYPE,
  SET_SIGN_IN_PASSWORD_TYPE,
  SET_LOGED_USER_TYPE,
  SET_SIGN_UP_ERRORS_TYPE,
  SET_EDIT_PROFILE_ERRORS_TYPE,
  SET_UNEXPECTED_ERROR_TYPE,
  ADD_TAG_TYPE,
  SET_TYPED_IN_TAG_TYPE,
  CLEAR_TYPED_IN_TAG_TYPE,
  DELETE_LAST_TAG_TYPE,
  SET_CREATE_ARTICLE_SUCCES_TYPE,
  SET_CREATE_ARTICLE_UNEXPECTED_ERROR_TYPE,
  SET_ARTICLE_TYPE,
  CLEAR_ARTICLE_TYPE,
  SET_ARTICLE_NOT_FOUND_TYPE,
  SET_ARTICLE_UNEXPECTED_ERROR_TYPE,
  SET_DELETE_ARTICLE_ERR_TYPE,
  SET_DELETE_ARTICLE_SUCCES_TYPE,
  TOOGLE_SHOW_DELETE_CONFIRM_TYPE,
  CLEAR_DELETE_ARTICLE_REDUCER_TYPE,
  CLEAR_CREATE_ARTICLE_REDUCER_TYPE,
};
